-- =============================================================
-- Regular Investor — Seed Data (37 articles)
-- Run after schema.sql
-- =============================================================

USE regular_investor;

INSERT INTO articles
  (id, title, excerpt, category, tag, date, slug, image, featured, read_time)
VALUES

-- ── ECONOMICS ────────────────────────────────────────────────
(1,
 'The Fed Pertimbangkan Kenaikan Suku Bunga Jika Inflasi Bertahan di Atas 2%',
 'Pejabat Federal Reserve memperingatkan bahwa kenaikan suku bunga mungkin diperlukan jika inflasi tetap di atas target 2%, berdasarkan risalah FOMC yang dirilis 20 Mei 2026.',
 'Economics', 'Global', '2026-05-21',
 'the-fed-pertimbangkan-kenaikan-suku-bunga',
 'https://regular-investor.com/wp-content/uploads/2026/05/FMOC-The-Fed.jpg',
 1, 4),

(6,
 'OJK Hapus Catatan Kredit di Bawah Rp1 Juta dari SLIK, Dorong Program 3 Juta Rumah',
 'Regulator keuangan menghapus catatan kredit di bawah Rp1 juta dari basis data kredit untuk mempercepat program tiga juta rumah pemerintah.',
 'Economics', 'Keuangan', '2026-04-17',
 'ojk-hapus-catatan-kredit-slik',
 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&auto=format&fit=crop',
 0, 3),

(8,
 'Lonjakan Restitusi PPN Batu Bara, DJP Pastikan Pemeriksaan Ketat',
 'Otoritas pajak memastikan verifikasi yang ketat atas meningkatnya klaim pengembalian PPN sektor batu bara.',
 'Economics', 'Pajak', '2026-05-06',
 'lonjakan-restitusi-ppn-batu-bara',
 'https://images.unsplash.com/photo-1611068661401-69e7f82e1d5a?w=800&auto=format&fit=crop',
 0, 3),

(9,
 'BI Rate Dipertahankan 5,75%, Gubernur BI: Prioritas Jaga Stabilitas Rupiah',
 'Bank Indonesia mempertahankan suku bunga acuan di level 5,75% dalam rapat dewan gubernur Mei 2026, dengan fokus menjaga stabilitas nilai tukar rupiah di tengah tekanan eksternal.',
 'Economics', 'Moneter', '2026-05-20',
 'bi-rate-dipertahankan-575-persen',
 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&auto=format&fit=crop',
 0, 4),

(10,
 'Inflasi Mei 2026 Tercatat 2,84%, Harga Pangan Masih Jadi Pendorong Utama',
 'BPS merilis data inflasi Mei 2026 sebesar 2,84% year-on-year, dengan kelompok makanan dan minuman masih menjadi penyumbang terbesar inflasi bulan ini.',
 'Economics', 'Makro', '2026-05-15',
 'inflasi-mei-2026-tercatat-284-persen',
 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&auto=format&fit=crop',
 0, 3),

(11,
 'Pertumbuhan Ekonomi Q1 2026 Capai 5,11%, Konsumsi Domestik Jadi Motor Utama',
 'Badan Pusat Statistik mengumumkan pertumbuhan ekonomi Indonesia kuartal pertama 2026 sebesar 5,11%, didukung konsumsi rumah tangga yang kuat dan belanja pemerintah.',
 'Economics', 'GDP', '2026-05-10',
 'pertumbuhan-ekonomi-q1-2026-capai-511',
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop',
 0, 5),

(12,
 'APBN Defisit Rp124 Triliun hingga April 2026, Penerimaan Pajak Tumbuh 8,2%',
 'Realisasi APBN hingga April 2026 mencatat defisit Rp124 triliun atau 0,56% dari PDB. Penerimaan pajak tumbuh 8,2% meski tekanan global masih terasa.',
 'Economics', 'Fiskal', '2026-05-08',
 'apbn-defisit-124-triliun-april-2026',
 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop',
 0, 4),

(13,
 'PMI Manufaktur Indonesia Mei 2026 Naik ke 52,3, Tertinggi dalam 8 Bulan',
 'Purchasing Managers'' Index sektor manufaktur Indonesia naik ke 52,3 pada Mei 2026, menandai ekspansi yang semakin kuat dan tertinggi dalam delapan bulan terakhir.',
 'Economics', 'Industri', '2026-05-02',
 'pmi-manufaktur-indonesia-mei-2026',
 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop',
 0, 3),

-- ── INVESTMENT ───────────────────────────────────────────────
(4,
 'Polemik Impor Minyak Indonesia-Rusia, Uni Eropa Geram Soal Shadow Fleet Karimun',
 'Indonesia dan Rusia sepakat pembelian 150 juta barel minyak dengan diskon 30-50%; Uni Eropa memprotes operasi shadow fleet di perairan Karimun.',
 'Investment', 'Energi', '2026-05-21',
 'polemik-impor-minyak-indonesia-rusia',
 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&auto=format&fit=crop',
 0, 6),

(5,
 'Fast Food Indonesia (FAST) Masih Rugi Rp366 Miliar di 2025, Auditor Soroti Going Concern',
 'Operator KFC Indonesia mencatat rugi Rp366 miliar di 2025, turun 54% dari tahun sebelumnya; auditor menyoroti masalah kelangsungan usaha.',
 'Investment', 'Saham', '2026-04-20',
 'fast-food-indonesia-rugi-366-miliar',
 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&auto=format&fit=crop',
 0, 4),

(7,
 'Rencana Bea Ekspor Pertambangan Berisiko Tekan Margin dan Profil Kredit Sektor Tambang',
 'Rencana penerapan bea ekspor pertambangan berisiko menekan margin dan profil kredit di seluruh sektor tambang Indonesia.',
 'Investment', 'Tambang', '2026-04-20',
 'bea-ekspor-pertambangan-tekan-margin',
 'https://images.unsplash.com/photo-1605188964787-7ef7f5a14cfa?w=800&auto=format&fit=crop',
 0, 5),

(14,
 'BBCA Bagikan Dividen Rp340 per Saham, Yield Capai 3,45% — Tanggal Cum-Div 5 Juni',
 'BCA mengumumkan pembagian dividen tunai Rp340 per lembar saham untuk tahun buku 2025. Dengan harga saham saat ini, dividend yield mencapai 3,45%.',
 'Investment', 'Dividen', '2026-05-19',
 'bbca-bagikan-dividen-340-per-saham',
 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&auto=format&fit=crop',
 1, 4),

(15,
 'Emas Dunia Tembus $3.200/Troy Ons, Analis: Masih Ada Ruang ke $3.500',
 'Harga emas spot menembus level psikologis $3.200 per troy ons, didorong pelemahan dolar AS dan meningkatnya permintaan safe haven akibat ketidakpastian geopolitik global.',
 'Investment', 'Emas', '2026-05-18',
 'emas-dunia-tembus-3200-troy-ons',
 'https://images.unsplash.com/photo-1610375461246-83df859d849d?w=800&auto=format&fit=crop',
 0, 5),

(16,
 'Bitcoin Capai $104.000, Sentimen Pasar Crypto Kembali Optimis Jelang Halving Kedua',
 'Bitcoin menyentuh level $104.000 setelah koreksi panjang, dengan volume perdagangan melonjak 40%. Analis memperkirakan momentum bullish berlanjut hingga akhir 2026.',
 'Investment', 'Kripto', '2026-05-17',
 'bitcoin-capai-104000-sentimen-optimis',
 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&auto=format&fit=crop',
 0, 4),

(17,
 'Reksa Dana Saham vs ETF: Mana Lebih Menguntungkan untuk Investor Jangka Panjang?',
 'Perbandingan komprehensif antara reksa dana saham aktif dan ETF pasif dalam konteks pasar Indonesia. Data 5 tahun menunjukkan ETF konsisten unggul dalam net return.',
 'Investment', 'Analisis', '2026-05-14',
 'reksa-dana-saham-vs-etf-perbandingan',
 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop',
 0, 8),

(18,
 'IHSG Tembus 7.300 untuk Pertama Kali, Asing Net Buy Rp2,1 Triliun',
 'Indeks Harga Saham Gabungan menembus level 7.300 untuk pertama kalinya dalam sejarah, didukung aliran modal asing masuk Rp2,1 triliun dalam satu sesi perdagangan.',
 'Investment', 'IHSG', '2026-05-12',
 'ihsg-tembus-7300-asing-net-buy',
 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop',
 0, 3),

-- ── NASIONAL ─────────────────────────────────────────────────
(2,
 'Menkeu Purbaya: Badan Ekspor SDA Dibentuk untuk Cegah Underinvoicing',
 'Menteri Keuangan Purbaya mengumumkan pembentukan Badan Ekspor SDA untuk mencegah praktik underinvoicing dalam ekspor komoditas, dengan potensi kebocoran mencapai US$150 miliar.',
 'Nasional', 'Kebijakan', '2026-05-21',
 'menkeu-purbaya-badan-ekspor-sda',
 'https://regular-investor.com/wp-content/uploads/2026/05/purbaya.jpeg',
 1, 5),

(19,
 'Prabowo Teken PP Hilirisasi Mineral, Ekspor Bahan Mentah Dilarang Mulai 2027',
 'Presiden Prabowo menandatangani Peraturan Pemerintah tentang hilirisasi mineral, mewajibkan semua komoditas tambang diolah dalam negeri sebelum diekspor mulai 1 Januari 2027.',
 'Nasional', 'Regulasi', '2026-05-20',
 'prabowo-teken-pp-hilirisasi-mineral',
 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&auto=format&fit=crop',
 0, 5),

(20,
 'Indef: Pemerintah Belum Optimal Tangkap Windfall Lonjakan Harga Komoditas',
 'Institute for Development of Economics and Finance menyatakan pemerintah melewatkan potensi penerimaan Rp192 triliun akibat belum optimalnya pengelolaan windfall komoditas.',
 'Nasional', 'Analisis', '2026-04-20',
 'indef-pemerintah-belum-optimal-windfall',
 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop',
 0, 4),

(21,
 'Proyek MRT Jakarta Fase 3 Mulai Konstruksi, Telan Investasi Rp42 Triliun',
 'Groundbreaking MRT Jakarta fase 3 (Cikarang–Balaraja) resmi dimulai dengan total investasi Rp42 triliun. Diperkirakan selesai pada 2030 dan melayani 1,2 juta penumpang per hari.',
 'Nasional', 'Infrastruktur', '2026-05-16',
 'mrt-jakarta-fase-3-mulai-konstruksi',
 'https://images.unsplash.com/photo-1614350292382-c448d0110dfa?w=800&auto=format&fit=crop',
 0, 4),

(22,
 'Reformasi Pajak 2026: Tarif PPh Badan Turun ke 20%, Insentif UMKM Diperluas',
 'Pemerintah resmi memangkas tarif PPh Badan dari 22% menjadi 20% sebagai bagian paket reformasi perpajakan, disertai perluasan insentif pajak untuk UMKM dan startup.',
 'Nasional', 'Pajak', '2026-05-13',
 'reformasi-pajak-2026-tarif-pph-badan',
 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&auto=format&fit=crop',
 0, 5),

(23,
 'Sovereign Wealth Fund Indonesia Capai AUM $40 Miliar, Fokus ke Infrastruktur Hijau',
 'Danantara Indonesia mencatatkan asset under management $40 miliar dalam setahun beroperasi, dengan alokasi terbesar ke proyek energi terbarukan dan infrastruktur hijau.',
 'Nasional', 'Investasi', '2026-05-11',
 'sovereign-wealth-fund-indonesia-40-miliar',
 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop',
 0, 6),

(24,
 'Cadangan Devisa Indonesia Naik ke $154 Miliar, Tertinggi Sejak 2013',
 'Bank Indonesia melaporkan cadangan devisa naik ke $154,2 miliar per akhir April 2026, level tertinggi sejak 2013, cukup untuk 6,8 bulan impor.',
 'Nasional', 'Makro', '2026-05-09',
 'cadangan-devisa-indonesia-154-miliar',
 'https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=800&auto=format&fit=crop',
 0, 3),

-- ── GLOBAL ───────────────────────────────────────────────────
(3,
 'Trump Yakin Konflik dengan Iran Segera Berakhir, Rusia Tegaskan Dukungan Penuh',
 'Presiden AS menyatakan optimismenya bahwa ketegangan dengan Iran akan segera terselesaikan, sementara Rusia mempertegas komitmennya untuk mendukung Teheran secara diplomatik.',
 'Global', 'Geopolitik', '2026-05-21',
 'trump-konflik-iran-segera-berakhir',
 'https://regular-investor.com/wp-content/uploads/2025/06/Trump-Angry-Getty.jpg',
 0, 3),

(25,
 'Menlu Iran Bertemu Wang Yi di Beijing, Hubungan Iran-China Kian Erat Jelang KTT Trump-Xi',
 'Menteri Luar Negeri Iran melakukan kunjungan ke Beijing dan bertemu Menlu China Wang Yi, memperkuat kemitraan strategis menjelang pertemuan puncak Trump-Xi.',
 'Global', 'Diplomasi', '2026-05-06',
 'menlu-iran-bertemu-wang-yi-beijing',
 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&auto=format&fit=crop',
 0, 4),

(26,
 'Fed Minutes: Pejabat Khawatir Stagflasi, Opsi Suku Bunga Terbagi Dua Kubu',
 'Risalah rapat FOMC mengungkapkan kekhawatiran mendalam soal stagflasi. Dua kubu terpecah: satu ingin tahan suku bunga, yang lain siap naikkan jika inflasi memburuk.',
 'Global', 'Fed', '2026-05-20',
 'fed-minutes-kekhawatiran-stagflasi',
 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=800&auto=format&fit=crop',
 0, 5),

(27,
 'Perang Dagang AS-China Babak Baru: Tarif Chip Naik 35%, Teknologi Makin Terancam',
 'Washington menaikkan tarif impor semikonduktor asal China menjadi 35%, memicu kekhawatiran baru atas rantai pasokan global dan prospek industri teknologi.',
 'Global', 'Perdagangan', '2026-05-15',
 'perang-dagang-as-china-tarif-chip-35-persen',
 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop',
 0, 6),

(28,
 'ECB Pangkas Suku Bunga 25 bps ke 2,5%, Inflasi Zona Euro Mendekati Target',
 'Bank Sentral Eropa memangkas suku bunga acuan sebesar 25 basis poin menjadi 2,5%, setelah inflasi zona Euro turun ke 2,1% mendekati target 2%.',
 'Global', 'Moneter', '2026-05-12',
 'ecb-pangkas-suku-bunga-25-bps',
 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&auto=format&fit=crop',
 0, 4),

(29,
 'Resesi Jepang Berakhir, GDP Q1 Tumbuh 1,2% Didorong Ekspor dan Wisatawan',
 'Jepang keluar dari resesi teknis setelah GDP kuartal pertama 2026 tumbuh 1,2% QoQ, didukung lonjakan ekspor otomotif dan rekor wisatawan mancanegara.',
 'Global', 'Asia', '2026-05-09',
 'resesi-jepang-berakhir-gdp-q1-12-persen',
 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop',
 0, 4),

(30,
 'OPEC+ Perpanjang Pemangkasan Produksi hingga Q4 2026, Harga Minyak Merespons',
 'OPEC+ sepakat memperpanjang pemangkasan produksi minyak sukarela 2,2 juta barel per hari hingga akhir kuartal keempat 2026, mendorong harga Brent melonjak 3%.',
 'Global', 'Energi', '2026-05-05',
 'opec-plus-perpanjang-pemangkasan-produksi-q4-2026',
 'https://images.unsplash.com/photo-1568952433726-3896e3881c65?w=800&auto=format&fit=crop',
 0, 4),

-- ── TECHNOLOGY ───────────────────────────────────────────────
(31,
 'GoTo Umumkan Profitabilitas Pertama, Laba Bersih Q1 2026 Capai Rp420 Miliar',
 'GOTO Group untuk pertama kalinya mencatatkan laba bersih sebesar Rp420 miliar pada kuartal pertama 2026, menandai titik balik setelah empat tahun kerugian beruntun.',
 'Technology', 'Startup', '2026-05-20',
 'goto-profitabilitas-pertama-laba-q1-2026',
 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&auto=format&fit=crop',
 1, 5),

(32,
 'AI Generatif Masuk Bursa: Microsoft dan Google Bersaing Rebut Pasar Enterprise Asia',
 'Microsoft Azure OpenAI dan Google Gemini Enterprise memperketat persaingan di pasar Asia Tenggara, dengan Indonesia sebagai target ekspansi terbesar di 2026.',
 'Technology', 'AI', '2026-05-18',
 'ai-generatif-microsoft-google-pasar-enterprise-asia',
 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&auto=format&fit=crop',
 0, 6),

(33,
 'Tokopedia Merger dengan TikTok Shop Capai GMV $12 Miliar, Ungguli Shopee',
 'Entitas gabungan Tokopedia-TikTok Shop mencatatkan Gross Merchandise Value $12 miliar dalam 12 bulan beroperasi, melampaui Shopee untuk pertama kalinya di Indonesia.',
 'Technology', 'E-Commerce', '2026-05-16',
 'tokopedia-tiktok-shop-gmv-12-miliar',
 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&auto=format&fit=crop',
 0, 5),

(34,
 'Telkom IndiHome Hadirkan Internet 10 Gbps, Harga Mulai Rp2,5 Juta/Bulan',
 'Telkom Indonesia meluncurkan layanan internet rumahan 10 Gbps pertama di Indonesia melalui IndiHome Fiber X, menargetkan segmen premium di 50 kota besar.',
 'Technology', 'Telekomunikasi', '2026-05-14',
 'telkom-indihome-internet-10-gbps',
 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop',
 0, 3),

(35,
 'Startup Fintech RI Raup Pendanaan $280 Juta di Q1 2026, Sektor BNPL Paling Diminati',
 'Ekosistem fintech Indonesia berhasil menarik investasi $280 juta pada kuartal pertama 2026. BNPL (Buy Now Pay Later) dan embedded finance menjadi segmen paling diminati investor.',
 'Technology', 'Fintech', '2026-05-10',
 'startup-fintech-ri-pendanaan-280-juta-q1-2026',
 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&auto=format&fit=crop',
 0, 5),

(36,
 'Indonesia Luncurkan Satelit GovSat-1, Perkuat Kedaulatan Digital Nasional',
 'Indonesia sukses meluncurkan satelit pemerintah GovSat-1 dari Cape Canaveral menggunakan roket SpaceX Falcon 9, memperkuat infrastruktur komunikasi dan keamanan nasional.',
 'Technology', 'Satelit', '2026-05-07',
 'indonesia-luncurkan-satelit-govsat-1',
 'https://images.unsplash.com/photo-1516849677043-ef67c9557e16?w=800&auto=format&fit=crop',
 0, 4),

(37,
 'Regulasi AI Indonesia 2026: Pemerintah Wajibkan Audit Etika untuk Sistem AI Kritis',
 'Kementerian Kominfo menerbitkan Peraturan Menteri tentang tata kelola AI, mewajibkan audit etika independen untuk sistem kecerdasan buatan yang digunakan di sektor keuangan dan kesehatan.',
 'Technology', 'Regulasi', '2026-05-04',
 'regulasi-ai-indonesia-2026-audit-etika',
 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop',
 0, 5);
